version: "3.9"
services:
  backend:
    build: 
      context: ./backend
      cache_to:
        - type=local,dest=data/cache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      start_period: 10s

volumes:
  db:
    driver: local